In [1]:
# import the tensorflow library
import tensorflow as tf
print(tf.__version__)

2.0.0


In [2]:
# import libraries
import numpy as np
import keras

Using TensorFlow backend.


In [3]:
# define the input and output variables
x = np.array([-2.0, -1.0, 2.0, 4.0, 5.0, 7.0])
y = np.array([-13.0, -10.0, -1.0, 5.0, 8.0, 14.0])

In [4]:
# initialize the keras sequential model with one dense layer and one input
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

In [5]:
# train the model with optimizer and loss 
model.compile(optimizer='sgd', loss='mean_squared_error')

In [6]:
# fit the model and train it with 500 epochs
model.fit(x, y, epochs=500)

Epoch 1/500
6/6 [==============================] - 0s 8ms/step - loss: 251.3237
Epoch 2/500
6/6 [==============================] - 0s 357us/step - loss: 129.2619
Epoch 3/500
6/6 [==============================] - 0s 333us/step - loss: 75.2871
Epoch 4/500
6/6 [==============================] - 0s 501us/step - loss: 51.1742
Epoch 5/500
6/6 [==============================] - 0s 666us/step - loss: 40.1644
Epoch 6/500
6/6 [==============================] - 0s 833us/step - loss: 34.9097
Epoch 7/500
6/6 [==============================] - 0s 498us/step - loss: 32.1886
Epoch 8/500
6/6 [==============================] - 0s 501us/step - loss: 30.5884
Epoch 9/500
6/6 [==============================] - 0s 667us/step - loss: 29.4893
Epoch 10/500
6/6 [==============================] - 0s 499us/step - loss: 28.6196
Epoch 11/500
6/6 [==============================] - 0s 832us/step - loss: 27.8598
Epoch 12/500
6/6 [==============================] - 0s 333us/step - loss: 27.1573
Epoch 13/500
6/6 [=======

Epoch 102/500
6/6 [==============================] - 0s 334us/step - loss: 3.0134
Epoch 103/500
6/6 [==============================] - 0s 333us/step - loss: 2.9407
Epoch 104/500
6/6 [==============================] - 0s 500us/step - loss: 2.8698
Epoch 105/500
6/6 [==============================] - 0s 666us/step - loss: 2.8005
Epoch 106/500
6/6 [==============================] - 0s 667us/step - loss: 2.7330
Epoch 107/500
6/6 [==============================] - 0s 333us/step - loss: 2.6670
Epoch 108/500
6/6 [==============================] - 0s 499us/step - loss: 2.6027
Epoch 109/500
6/6 [==============================] - 0s 333us/step - loss: 2.5399
Epoch 110/500
6/6 [==============================] - 0s 833us/step - loss: 2.4787
Epoch 111/500
6/6 [==============================] - 0s 1ms/step - loss: 2.4189
Epoch 112/500
6/6 [==============================] - 0s 333us/step - loss: 2.3605
Epoch 113/500
6/6 [==============================] - 0s 667us/step - loss: 2.3036
Epoch 114/500
6/6 

Epoch 203/500
6/6 [==============================] - 0s 1ms/step - loss: 0.2558
Epoch 204/500
6/6 [==============================] - 0s 500us/step - loss: 0.2497
Epoch 205/500
6/6 [==============================] - 0s 334us/step - loss: 0.2436
Epoch 206/500
6/6 [==============================] - 0s 833us/step - loss: 0.2378
Epoch 207/500
6/6 [==============================] - 0s 335us/step - loss: 0.2320
Epoch 208/500
6/6 [==============================] - 0s 333us/step - loss: 0.2264
Epoch 209/500
6/6 [==============================] - 0s 500us/step - loss: 0.2210
Epoch 210/500
6/6 [==============================] - 0s 501us/step - loss: 0.2156
Epoch 211/500
6/6 [==============================] - 0s 333us/step - loss: 0.2104
Epoch 212/500
6/6 [==============================] - 0s 334us/step - loss: 0.2054
Epoch 213/500
6/6 [==============================] - 0s 334us/step - loss: 0.2004
Epoch 214/500
6/6 [==============================] - 0s 333us/step - loss: 0.1956
Epoch 215/500
6/6 

Epoch 304/500
6/6 [==============================] - 0s 334us/step - loss: 0.0217
Epoch 305/500
6/6 [==============================] - 0s 333us/step - loss: 0.0212
Epoch 306/500
6/6 [==============================] - 0s 667us/step - loss: 0.0207
Epoch 307/500
6/6 [==============================] - 0s 500us/step - loss: 0.0202
Epoch 308/500
6/6 [==============================] - 0s 333us/step - loss: 0.0197
Epoch 309/500
6/6 [==============================] - 0s 333us/step - loss: 0.0192
Epoch 310/500
6/6 [==============================] - 0s 334us/step - loss: 0.0188
Epoch 311/500
6/6 [==============================] - 0s 500us/step - loss: 0.0183
Epoch 312/500
6/6 [==============================] - 0s 537us/step - loss: 0.0179
Epoch 313/500
6/6 [==============================] - 0s 500us/step - loss: 0.0174
Epoch 314/500
6/6 [==============================] - 0s 666us/step - loss: 0.0170
Epoch 315/500
6/6 [==============================] - 0s 871us/step - loss: 0.0166
Epoch 316/500
6/

Epoch 405/500
6/6 [==============================] - 0s 333us/step - loss: 0.0018
Epoch 406/500
6/6 [==============================] - 0s 332us/step - loss: 0.0018
Epoch 407/500
6/6 [==============================] - 0s 666us/step - loss: 0.0018
Epoch 408/500
6/6 [==============================] - 0s 334us/step - loss: 0.0017
Epoch 409/500
6/6 [==============================] - 0s 500us/step - loss: 0.0017
Epoch 410/500
6/6 [==============================] - 0s 338us/step - loss: 0.0016
Epoch 411/500
6/6 [==============================] - 0s 334us/step - loss: 0.0016
Epoch 412/500
6/6 [==============================] - 0s 334us/step - loss: 0.0016
Epoch 413/500
6/6 [==============================] - 0s 332us/step - loss: 0.0015
Epoch 414/500
6/6 [==============================] - 0s 833us/step - loss: 0.0015
Epoch 415/500
6/6 [==============================] - 0s 501us/step - loss: 0.0014
Epoch 416/500
6/6 [==============================] - 0s 334us/step - loss: 0.0014
Epoch 417/500
6/

In [7]:
# model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [8]:
# predict the new input 
model.predict([9.0])

array([[19.992989]], dtype=float32)

In [9]:
# predict another input
model.predict([40.0])

array([[112.91074]], dtype=float32)

In [10]:
# predict with multiple inputs
model.predict([10.0, 11.0, 15.0])

array([[22.990335],
       [25.987684],
       [37.977074]], dtype=float32)

#### This is also called as the Hello world program of the tensorflow keras sequential model.
#### In this we used optimizer 'sgd' to optimize the result w.r.t loss function which is mean_squared_error by reducing the error.

### Housing Price Prediction with one feature

In this example you'll try to build a neural network that predicts the price of a house according to a simple formula.

So, imagine if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down. You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [11]:
housing_model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])# Your Code Here#

In [12]:
housing_model.compile(optimizer='sgd', loss='mean_squared_error')# Your Code Here#)

In [13]:
xs = np.array([1.0,2.0,3.0,5.0,6.0])# Your Code Here#
ys = np.array([100.0, 150.0, 200.0, 300.0, 350.0])# Your Code Here#

In [14]:
housing_model.fit(xs, ys, epochs=700) # Your Code here#)

Epoch 1/700
5/5 [==============================] - 0s 8ms/step - loss: 56621.9688
Epoch 2/700
5/5 [==============================] - 0s 400us/step - loss: 26679.6348
Epoch 3/700
5/5 [==============================] - 0s 400us/step - loss: 12654.8076
Epoch 4/700
5/5 [==============================] - 0s 400us/step - loss: 6084.9258
Epoch 5/700
5/5 [==============================] - 0s 801us/step - loss: 3006.5583
Epoch 6/700
5/5 [==============================] - 0s 599us/step - loss: 1563.4500
Epoch 7/700
5/5 [==============================] - 0s 1ms/step - loss: 886.2220
Epoch 8/700
5/5 [==============================] - 0s 601us/step - loss: 567.7037
Epoch 9/700
5/5 [==============================] - 0s 592us/step - loss: 417.1983
Epoch 10/700
5/5 [==============================] - 0s 800us/step - loss: 345.3934
Epoch 11/700
5/5 [==============================] - 0s 399us/step - loss: 310.4586
Epoch 12/700
5/5 [==============================] - 0s 601us/step - loss: 292.8033
Epoch 13

Epoch 101/700
5/5 [==============================] - 0s 600us/step - loss: 128.3825
Epoch 102/700
5/5 [==============================] - 0s 401us/step - loss: 127.2657
Epoch 103/700
5/5 [==============================] - 0s 601us/step - loss: 126.1585
Epoch 104/700
5/5 [==============================] - 0s 347us/step - loss: 125.0609
Epoch 105/700
5/5 [==============================] - 0s 1ms/step - loss: 123.9728
Epoch 106/700
5/5 [==============================] - 0s 800us/step - loss: 122.8942
Epoch 107/700
5/5 [==============================] - 0s 600us/step - loss: 121.8251
Epoch 108/700
5/5 [==============================] - 0s 600us/step - loss: 120.7653
Epoch 109/700
5/5 [==============================] - 0s 399us/step - loss: 119.7147
Epoch 110/700
5/5 [==============================] - 0s 1ms/step - loss: 118.6732
Epoch 111/700
5/5 [==============================] - 0s 601us/step - loss: 117.6407
Epoch 112/700
5/5 [==============================] - 0s 799us/step - loss: 116.6

Epoch 200/700
5/5 [==============================] - 0s 400us/step - loss: 54.0531
Epoch 201/700
5/5 [==============================] - 0s 570us/step - loss: 53.5829
Epoch 202/700
5/5 [==============================] - 0s 606us/step - loss: 53.1167
Epoch 203/700
5/5 [==============================] - 0s 400us/step - loss: 52.6547
Epoch 204/700
5/5 [==============================] - 0s 600us/step - loss: 52.1965
Epoch 205/700
5/5 [==============================] - 0s 400us/step - loss: 51.7424
Epoch 206/700
5/5 [==============================] - 0s 399us/step - loss: 51.2924
Epoch 207/700
5/5 [==============================] - 0s 600us/step - loss: 50.8461
Epoch 208/700
5/5 [==============================] - 0s 400us/step - loss: 50.4037
Epoch 209/700
5/5 [==============================] - 0s 600us/step - loss: 49.9652
Epoch 210/700
5/5 [==============================] - 0s 600us/step - loss: 49.5305
Epoch 211/700
5/5 [==============================] - 0s 395us/step - loss: 49.0997
Epoc

Epoch 299/700
5/5 [==============================] - 0s 1ms/step - loss: 22.7582
Epoch 300/700
5/5 [==============================] - 0s 399us/step - loss: 22.5602
Epoch 301/700
5/5 [==============================] - 0s 400us/step - loss: 22.3639
Epoch 302/700
5/5 [==============================] - 0s 800us/step - loss: 22.1693
Epoch 303/700
5/5 [==============================] - 0s 1000us/step - loss: 21.9765
Epoch 304/700
5/5 [==============================] - 0s 800us/step - loss: 21.7853
Epoch 305/700
5/5 [==============================] - 0s 600us/step - loss: 21.5958
Epoch 306/700
5/5 [==============================] - 0s 600us/step - loss: 21.4078
Epoch 307/700
5/5 [==============================] - 0s 800us/step - loss: 21.2217
Epoch 308/700
5/5 [==============================] - 0s 600us/step - loss: 21.0370
Epoch 309/700
5/5 [==============================] - 0s 202us/step - loss: 20.8540
Epoch 310/700
5/5 [==============================] - 0s 400us/step - loss: 20.6725
Epoch

Epoch 398/700
5/5 [==============================] - 0s 400us/step - loss: 9.5819
Epoch 399/700
5/5 [==============================] - 0s 599us/step - loss: 9.4985
Epoch 400/700
5/5 [==============================] - 0s 245us/step - loss: 9.4159
Epoch 401/700
5/5 [==============================] - 0s 600us/step - loss: 9.3340
Epoch 402/700
5/5 [==============================] - 0s 1ms/step - loss: 9.2528
Epoch 403/700
5/5 [==============================] - 0s 317us/step - loss: 9.1723
Epoch 404/700
5/5 [==============================] - 0s 599us/step - loss: 9.0925
Epoch 405/700
5/5 [==============================] - 0s 799us/step - loss: 9.0134
Epoch 406/700
5/5 [==============================] - 0s 800us/step - loss: 8.9350
Epoch 407/700
5/5 [==============================] - 0s 799us/step - loss: 8.8572
Epoch 408/700
5/5 [==============================] - 0s 599us/step - loss: 8.7802
Epoch 409/700
5/5 [==============================] - 0s 2ms/step - loss: 8.7038
Epoch 410/700
5/5 [=

Epoch 499/700
5/5 [==============================] - 0s 400us/step - loss: 3.9644
Epoch 500/700
5/5 [==============================] - 0s 801us/step - loss: 3.9299
Epoch 501/700
5/5 [==============================] - 0s 600us/step - loss: 3.8958
Epoch 502/700
5/5 [==============================] - 0s 1ms/step - loss: 3.8619
Epoch 503/700
5/5 [==============================] - 0s 800us/step - loss: 3.8282
Epoch 504/700
5/5 [==============================] - 0s 600us/step - loss: 3.7950
Epoch 505/700
5/5 [==============================] - 0s 601us/step - loss: 3.7620
Epoch 506/700
5/5 [==============================] - 0s 599us/step - loss: 3.7292
Epoch 507/700
5/5 [==============================] - 0s 600us/step - loss: 3.6968
Epoch 508/700
5/5 [==============================] - 0s 602us/step - loss: 3.6646
Epoch 509/700
5/5 [==============================] - 0s 600us/step - loss: 3.6327
Epoch 510/700
5/5 [==============================] - 0s 800us/step - loss: 3.6011
Epoch 511/700
5/5 

Epoch 600/700
5/5 [==============================] - 0s 400us/step - loss: 1.6402
Epoch 601/700
5/5 [==============================] - 0s 1ms/step - loss: 1.6260
Epoch 602/700
5/5 [==============================] - 0s 600us/step - loss: 1.6118
Epoch 603/700
5/5 [==============================] - 0s 601us/step - loss: 1.5978
Epoch 604/700
5/5 [==============================] - 0s 600us/step - loss: 1.5839
Epoch 605/700
5/5 [==============================] - 0s 800us/step - loss: 1.5701
Epoch 606/700
5/5 [==============================] - 0s 600us/step - loss: 1.5565
Epoch 607/700
5/5 [==============================] - 0s 433us/step - loss: 1.5429
Epoch 608/700
5/5 [==============================] - 0s 399us/step - loss: 1.5295
Epoch 609/700
5/5 [==============================] - 0s 800us/step - loss: 1.5162
Epoch 610/700
5/5 [==============================] - 0s 400us/step - loss: 1.5030
Epoch 611/700
5/5 [==============================] - 0s 800us/step - loss: 1.4899
Epoch 612/700
5/5 

In [15]:
print(housing_model.predict([7.0]))

[[401.0491]]


In [16]:
print(housing_model.predict([8.0, 9.0, 10.0]))

[[451.4446 ]
 [501.84012]
 [552.23566]]
