In [1]:
# import the tensorflow library
import tensorflow as tf
print(tf.__version__)

2.0.0


In [4]:
# import libraries
import numpy as np
import keras

Using TensorFlow backend.


In [3]:
# define the input and output variables
x = np.array([-2.0, -1.0, 2.0, 4.0, 5.0, 7.0])
y = np.array([-13.0, -10.0, -1.0, 5.0, 8.0, 14.0])

In [10]:
# initialize the keras sequential model with one dense layer and one input
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])

In [11]:
# train the model with optimizer and loss 
model.compile(optimizer='sgd', loss='mean_squared_error')

In [12]:
# fit the model and train it with 500 epochs
model.fit(x, y, epochs=500)

Epoch 1/500
6/6 [==============================] - 0s 17ms/step - loss: 77.3037
Epoch 2/500
6/6 [==============================] - 0s 334us/step - loss: 51.4685
Epoch 3/500
6/6 [==============================] - 0s 502us/step - loss: 39.7178
Epoch 4/500
6/6 [==============================] - 0s 333us/step - loss: 34.1522
Epoch 5/500
6/6 [==============================] - 0s 666us/step - loss: 31.3084
Epoch 6/500
6/6 [==============================] - 0s 667us/step - loss: 29.6675
Epoch 7/500
6/6 [==============================] - 0s 501us/step - loss: 28.5636
Epoch 8/500
6/6 [==============================] - 0s 499us/step - loss: 27.7043
Epoch 9/500
6/6 [==============================] - 0s 501us/step - loss: 26.9614
Epoch 10/500
6/6 [==============================] - 0s 678us/step - loss: 26.2783
Epoch 11/500
6/6 [==============================] - 0s 500us/step - loss: 25.6300
Epoch 12/500
6/6 [==============================] - 0s 666us/step - loss: 25.0055
Epoch 13/500
6/6 [========

Epoch 102/500
6/6 [==============================] - 0s 334us/step - loss: 2.7766
Epoch 103/500
6/6 [==============================] - 0s 672us/step - loss: 2.7096
Epoch 104/500
6/6 [==============================] - 0s 501us/step - loss: 2.6442
Epoch 105/500
6/6 [==============================] - 0s 500us/step - loss: 2.5805
Epoch 106/500
6/6 [==============================] - 0s 832us/step - loss: 2.5182
Epoch 107/500
6/6 [==============================] - 0s 333us/step - loss: 2.4575
Epoch 108/500
6/6 [==============================] - 0s 667us/step - loss: 2.3982
Epoch 109/500
6/6 [==============================] - 0s 500us/step - loss: 2.3403
Epoch 110/500
6/6 [==============================] - 0s 334us/step - loss: 2.2839
Epoch 111/500
6/6 [==============================] - 0s 333us/step - loss: 2.2288
Epoch 112/500
6/6 [==============================] - 0s 500us/step - loss: 2.1750
Epoch 113/500
6/6 [==============================] - 0s 1000us/step - loss: 2.1226
Epoch 114/500
6

Epoch 202/500
6/6 [==============================] - 0s 1ms/step - loss: 0.2416
Epoch 203/500
6/6 [==============================] - 0s 333us/step - loss: 0.2357
Epoch 204/500
6/6 [==============================] - 0s 666us/step - loss: 0.2300
Epoch 205/500
6/6 [==============================] - 0s 500us/step - loss: 0.2245
Epoch 206/500
6/6 [==============================] - 0s 845us/step - loss: 0.2191
Epoch 207/500
6/6 [==============================] - 0s 333us/step - loss: 0.2138
Epoch 208/500
6/6 [==============================] - 0s 500us/step - loss: 0.2086
Epoch 209/500
6/6 [==============================] - 0s 333us/step - loss: 0.2036
Epoch 210/500
6/6 [==============================] - 0s 833us/step - loss: 0.1987
Epoch 211/500
6/6 [==============================] - 0s 500us/step - loss: 0.1939
Epoch 212/500
6/6 [==============================] - 0s 500us/step - loss: 0.1892
Epoch 213/500
6/6 [==============================] - 0s 500us/step - loss: 0.1847
Epoch 214/500
6/6 

6/6 [==============================] - 0s 667us/step - loss: 0.0210
Epoch 303/500
6/6 [==============================] - 0s 1ms/step - loss: 0.0205
Epoch 304/500
6/6 [==============================] - 0s 666us/step - loss: 0.0200
Epoch 305/500
6/6 [==============================] - 0s 667us/step - loss: 0.0195
Epoch 306/500
6/6 [==============================] - 0s 333us/step - loss: 0.0191
Epoch 307/500
6/6 [==============================] - 0s 500us/step - loss: 0.0186
Epoch 308/500
6/6 [==============================] - 0s 834us/step - loss: 0.0182
Epoch 309/500
6/6 [==============================] - 0s 334us/step - loss: 0.0177
Epoch 310/500
6/6 [==============================] - 0s 334us/step - loss: 0.0173
Epoch 311/500
6/6 [==============================] - 0s 500us/step - loss: 0.0169
Epoch 312/500
6/6 [==============================] - 0s 501us/step - loss: 0.0165
Epoch 313/500
6/6 [==============================] - 0s 999us/step - loss: 0.0161
Epoch 314/500
6/6 [=============

Epoch 403/500
6/6 [==============================] - 0s 833us/step - loss: 0.0018
Epoch 404/500
6/6 [==============================] - 0s 334us/step - loss: 0.0017
Epoch 405/500
6/6 [==============================] - 0s 666us/step - loss: 0.0017
Epoch 406/500
6/6 [==============================] - 0s 1ms/step - loss: 0.0017
Epoch 407/500
6/6 [==============================] - 0s 502us/step - loss: 0.0016
Epoch 408/500
6/6 [==============================] - 0s 499us/step - loss: 0.0016
Epoch 409/500
6/6 [==============================] - 0s 501us/step - loss: 0.0015
Epoch 410/500
6/6 [==============================] - 0s 499us/step - loss: 0.0015
Epoch 411/500
6/6 [==============================] - 0s 832us/step - loss: 0.0015
Epoch 412/500
6/6 [==============================] - 0s 333us/step - loss: 0.0014
Epoch 413/500
6/6 [==============================] - 0s 501us/step - loss: 0.0014
Epoch 414/500
6/6 [==============================] - 0s 335us/step - loss: 0.0014
Epoch 415/500
6/6 

Epoch 500/500
6/6 [==============================] - 0s 501us/step - loss: 1.6705e-04


In [15]:
# model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [14]:
# predict the new input 
model.predict([9.0])

array([[19.99327]], dtype=float32)

In [17]:
# predict another input
model.predict([40.0])

array([[112.91431]], dtype=float32)

In [19]:
# predict with multiple inputs
model.predict([10.0, 11.0, 15.0])

array([[22.990723],
       [25.988174],
       [37.97799 ]], dtype=float32)

#### This is also called as the Hello world program of the tensorflow keras sequential model.
#### In this we used optimizer 'sgd' to optimize the result w.r.t loss function which is mean_squared_error by reducing the error.

### Housing Price Prediction with one feature

In this example you'll try to build a neural network that predicts the price of a house according to a simple formula.

So, imagine if house pricing was as easy as a house costs 50k + 50k per bedroom, so that a 1 bedroom house costs 100k, a 2 bedroom house costs 150k etc.

How would you create a neural network that learns this relationship so that it would predict a 7 bedroom house as costing close to 400k etc.

Hint: Your network might work better if you scale the house price down. You don't have to give the answer 400...it might be better to create something that predicts the number 4, and then your answer is in the 'hundreds of thousands' etc.

In [50]:
housing_model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[1])])# Your Code Here#

In [51]:
housing_model.compile(optimizer='sgd', loss='mean_squared_error')# Your Code Here#)

In [52]:
xs = np.array([1.0,2.0,3.0,5.0,6.0])# Your Code Here#
ys = np.array([100.0, 150.0, 200.0, 300.0, 350.0])# Your Code Here#

In [53]:
housing_model.fit(xs, ys, epochs=700) # Your Code here#)

Epoch 1/700
5/5 [==============================] - 0s 8ms/step - loss: 57306.8633
Epoch 2/700
5/5 [==============================] - 0s 400us/step - loss: 26999.6875
Epoch 3/700
5/5 [==============================] - 0s 600us/step - loss: 12803.9990
Epoch 4/700
5/5 [==============================] - 0s 399us/step - loss: 6154.0962
Epoch 5/700
5/5 [==============================] - 0s 600us/step - loss: 3038.2610
Epoch 6/700
5/5 [==============================] - 0s 1ms/step - loss: 1577.6082
Epoch 7/700
5/5 [==============================] - 0s 400us/step - loss: 892.1688
Epoch 8/700
5/5 [==============================] - 0s 400us/step - loss: 569.8116
Epoch 9/700
5/5 [==============================] - 0s 812us/step - loss: 417.5139
Epoch 10/700
5/5 [==============================] - 0s 401us/step - loss: 344.8752
Epoch 11/700
5/5 [==============================] - 0s 600us/step - loss: 309.5558
Epoch 12/700
5/5 [==============================] - 0s 400us/step - loss: 291.7261
Epoch 13

Epoch 100/700
5/5 [==============================] - 0s 400us/step - loss: 128.9344
Epoch 101/700
5/5 [==============================] - 0s 599us/step - loss: 127.8127
Epoch 102/700
5/5 [==============================] - 0s 600us/step - loss: 126.7008
Epoch 103/700
5/5 [==============================] - 0s 400us/step - loss: 125.5985
Epoch 104/700
5/5 [==============================] - 0s 800us/step - loss: 124.5059
Epoch 105/700
5/5 [==============================] - 0s 1000us/step - loss: 123.4227
Epoch 106/700
5/5 [==============================] - 0s 399us/step - loss: 122.3489
Epoch 107/700
5/5 [==============================] - 0s 600us/step - loss: 121.2845
Epoch 108/700
5/5 [==============================] - 0s 599us/step - loss: 120.2294
Epoch 109/700
5/5 [==============================] - 0s 600us/step - loss: 119.1835
Epoch 110/700
5/5 [==============================] - 0s 400us/step - loss: 118.1465
Epoch 111/700
5/5 [==============================] - 0s 600us/step - loss: 

Epoch 199/700
5/5 [==============================] - 0s 600us/step - loss: 54.2855
Epoch 200/700
5/5 [==============================] - 0s 600us/step - loss: 53.8132
Epoch 201/700
5/5 [==============================] - 0s 798us/step - loss: 53.3450
Epoch 202/700
5/5 [==============================] - 0s 600us/step - loss: 52.8810
Epoch 203/700
5/5 [==============================] - 0s 399us/step - loss: 52.4209
Epoch 204/700
5/5 [==============================] - 0s 400us/step - loss: 51.9648
Epoch 205/700
5/5 [==============================] - 0s 601us/step - loss: 51.5128
Epoch 206/700
5/5 [==============================] - 0s 600us/step - loss: 51.0646
Epoch 207/700
5/5 [==============================] - 0s 604us/step - loss: 50.6204
Epoch 208/700
5/5 [==============================] - 0s 401us/step - loss: 50.1800
Epoch 209/700
5/5 [==============================] - 0s 399us/step - loss: 49.7435
Epoch 210/700
5/5 [==============================] - 0s 600us/step - loss: 49.3107
Epoc

Epoch 298/700
5/5 [==============================] - 0s 601us/step - loss: 22.8560
Epoch 299/700
5/5 [==============================] - 0s 600us/step - loss: 22.6570
Epoch 300/700
5/5 [==============================] - 0s 601us/step - loss: 22.4600
Epoch 301/700
5/5 [==============================] - 0s 599us/step - loss: 22.2646
Epoch 302/700
5/5 [==============================] - 0s 600us/step - loss: 22.0709
Epoch 303/700
5/5 [==============================] - 0s 600us/step - loss: 21.8789
Epoch 304/700
5/5 [==============================] - 0s 601us/step - loss: 21.6886
Epoch 305/700
5/5 [==============================] - 0s 2ms/step - loss: 21.4998
Epoch 306/700
5/5 [==============================] - 0s 399us/step - loss: 21.3128
Epoch 307/700
5/5 [==============================] - 0s 600us/step - loss: 21.1273
Epoch 308/700
5/5 [==============================] - 0s 400us/step - loss: 20.9436
Epoch 309/700
5/5 [==============================] - 0s 600us/step - loss: 20.7614
Epoch 

5/5 [==============================] - 0s 601us/step - loss: 9.6231
Epoch 398/700
5/5 [==============================] - 0s 600us/step - loss: 9.5394
Epoch 399/700
5/5 [==============================] - 0s 400us/step - loss: 9.4564
Epoch 400/700
5/5 [==============================] - 0s 600us/step - loss: 9.3741
Epoch 401/700
5/5 [==============================] - 0s 600us/step - loss: 9.2926
Epoch 402/700
5/5 [==============================] - 0s 400us/step - loss: 9.2117
Epoch 403/700
5/5 [==============================] - 0s 800us/step - loss: 9.1316
Epoch 404/700
5/5 [==============================] - 0s 800us/step - loss: 9.0522
Epoch 405/700
5/5 [==============================] - 0s 400us/step - loss: 8.9734
Epoch 406/700
5/5 [==============================] - 0s 600us/step - loss: 8.8953
Epoch 407/700
5/5 [==============================] - 0s 800us/step - loss: 8.8179
Epoch 408/700
5/5 [==============================] - 0s 799us/step - loss: 8.7412
Epoch 409/700
5/5 [===========

Epoch 498/700
5/5 [==============================] - 0s 400us/step - loss: 3.9815
Epoch 499/700
5/5 [==============================] - 0s 685us/step - loss: 3.9468
Epoch 500/700
5/5 [==============================] - 0s 201us/step - loss: 3.9125
Epoch 501/700
5/5 [==============================] - 0s 800us/step - loss: 3.8785
Epoch 502/700
5/5 [==============================] - 0s 400us/step - loss: 3.8447
Epoch 503/700
5/5 [==============================] - 0s 600us/step - loss: 3.8113
Epoch 504/700
5/5 [==============================] - 0s 401us/step - loss: 3.7781
Epoch 505/700
5/5 [==============================] - 0s 400us/step - loss: 3.7452
Epoch 506/700
5/5 [==============================] - 0s 600us/step - loss: 3.7127
Epoch 507/700
5/5 [==============================] - 0s 400us/step - loss: 3.6804
Epoch 508/700
5/5 [==============================] - 0s 600us/step - loss: 3.6483
Epoch 509/700
5/5 [==============================] - 0s 600us/step - loss: 3.6166
Epoch 510/700
5/

Epoch 599/700
5/5 [==============================] - 0s 800us/step - loss: 1.6473
Epoch 600/700
5/5 [==============================] - 0s 599us/step - loss: 1.6330
Epoch 601/700
5/5 [==============================] - 0s 401us/step - loss: 1.6188
Epoch 602/700
5/5 [==============================] - 0s 1ms/step - loss: 1.6047
Epoch 603/700
5/5 [==============================] - 0s 399us/step - loss: 1.5907
Epoch 604/700
5/5 [==============================] - 0s 400us/step - loss: 1.5769
Epoch 605/700
5/5 [==============================] - 0s 599us/step - loss: 1.5632
Epoch 606/700
5/5 [==============================] - 0s 400us/step - loss: 1.5496
Epoch 607/700
5/5 [==============================] - 0s 600us/step - loss: 1.5361
Epoch 608/700
5/5 [==============================] - 0s 523us/step - loss: 1.5227
Epoch 609/700
5/5 [==============================] - 0s 800us/step - loss: 1.5095
Epoch 610/700
5/5 [==============================] - 0s 801us/step - loss: 1.4963
Epoch 611/700
5/5 

Epoch 700/700
5/5 [==============================] - 0s 601us/step - loss: 0.6816


In [57]:
print(housing_model.predict([7.0]))

[[401.04672]]


In [58]:
print(housing_model.predict([8.0, 9.0, 10.0]))

[[451.44138]
 [501.83603]
 [552.23065]]
